name: Sync Version

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from release tag
        id: extract_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Update manifest.json
        run: |
          VERSION=${{ steps.extract_version.outputs.version }}
          jq ".version = \"$VERSION\"" manifest.json > manifest.tmp.json
          mv manifest.tmp.json manifest.json
        shell: bash

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifest.json
          git commit -m "Update manifest version to ${{ steps.extract_version.outputs.version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}